language: java
env:
  global:
    - SONATYPE_USERNAME=benoitx
    - secure: "U772V1+agW49XyvQ9OoSDJdXEqEyS/hJEEkUrwx9gUruMwG8AuzOr2LX1MdgVKeiCtdttQ4MYSHf3dDQVnBCPmn+yHPh0ceRN5MGFkuNj8yKmsqo3bkGd4ihutrBj4zHQOXCodFXGCMAMdWP3SDZsLj7rUiFjIvzyYhaQAwuSfo="
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - opensource@appendium.com
    on_success: always
after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { python travis/addServer.py; mvn clean deploy --settings ~/.m2/mySettings.xml; };"
